### ISSUE TITLE
MGARD compress-decompress is incorrect on some matrix sizes.

### ISSUE THREAD

**Issue by NAThompson** [CODARcode/MGARD#31] opened 2019-10-28 14:24 UTC
Code to reproduce:

```cpp
#include <vector>
#include <random>
#include <mgard_api.h>

void test_compress_decompress_at_zero_tolerance() {
    std::mt19937_64 gen(238412421);
    std::normal_distribution<double> dis(0,1);

    int F0 = 8;
    int F1 = 13;
    double tolerance = 1e-7;
    while(F1 < 30000) {
        size_t F2 = F1 + F0;

        int rows = std::floor(std::sqrt(F2));
        int cols = F2/rows;
        std::vector<double> v(rows*cols);
        for (auto & x : v) {
            x = dis(gen);
        }

        int out_size;

        std::cout << "Testing decompose-recompose satisfies tolerance on vector of size " << v.size() << " interpreted as a matrix of " << rows << " rows and " << cols << " cols\n";

        unsigned char * compressed_data = mgard_compress(1, v.data(), out_size,
                                                             rows, cols, 1, tolerance);

        double quantizer;
        double* w = mgard_decompress(1, quantizer, compressed_data, out_size, rows, cols, 1);
        if (w == nullptr) {
            throw std::domain_error("Pointer returned is null.");
        }
        for (size_t i = 0; i < v.size(); ++i) {
            if(std::abs(w[i] - v[i]) > tolerance) {
                std::cerr << "Expected = " << v[i] << ", but computed = " << w[i] << "\n";
            }
        }

        free(compressed_data);
        free(w);
        F0 = F1;
        F1 = F2;
    }
}

int main() {
    test_compress_decompress_at_zero_tolerance();
}
```

Output:

```
Testing decompose-recompose satisfies tolerance on vector of size 20 interpreted as a matrix of 4 rows and 5 cols
Testing decompose-recompose satisfies tolerance on vector of size 30 interpreted as a matrix of 5 rows and 6 cols
Testing decompose-recompose satisfies tolerance on vector of size 49 interpreted as a matrix of 7 rows and 7 cols
Testing decompose-recompose satisfies tolerance on vector of size 81 interpreted as a matrix of 9 rows and 9 cols
Expected = 2.05312, but computed = 2.05312
Testing decompose-recompose satisfies tolerance on vector of size 144 interpreted as a matrix of 12 rows and 12 cols
Testing decompose-recompose satisfies tolerance on vector of size 225 interpreted as a matrix of 15 rows and 15 cols
Testing decompose-recompose satisfies tolerance on vector of size 361 interpreted as a matrix of 19 rows and 19 cols
Testing decompose-recompose satisfies tolerance on vector of size 600 interpreted as a matrix of 24 rows and 25 cols
Testing decompose-recompose satisfies tolerance on vector of size 961 interpreted as a matrix of 31 rows and 31 cols
Testing decompose-recompose satisfies tolerance on vector of size 1560 interpreted as a matrix of 39 rows and 40 cols
Testing decompose-recompose satisfies tolerance on vector of size 2550 interpreted as a matrix of 50 rows and 51 cols
Testing decompose-recompose satisfies tolerance on vector of size 4160 interpreted as a matrix of 64 rows and 65 cols
Testing decompose-recompose satisfies tolerance on vector of size 6724 interpreted as a matrix of 82 rows and 82 cols
Testing decompose-recompose satisfies tolerance on vector of size 10920 interpreted as a matrix of 104 rows and 105 cols
Testing decompose-recompose satisfies tolerance on vector of size 17689 interpreted as a matrix of 133 rows and 133 cols
Testing decompose-recompose satisfies tolerance on vector of size 28561 interpreted as a matrix of 169 rows and 169 cols
Testing decompose-recompose satisfies tolerance on vector of size 46225 interpreted as a matrix of 215 rows and 215 cols
Expected = -1.11716, but computed = -0.855364
Expected = -1.30552, but computed = -0.781921
Expected = -1.48203, but computed = -1.22023
Expected = 0.251681, but computed = 0.775281
Expected = 2.38765, but computed = 3.43485
Expected = 0.287533, but computed = 0.811133
Expected = -0.558841, but computed = -0.297041
Expected = -1.03464, but computed = -0.511041
Expected = -1.17775, but computed = -0.91595
```

We have also tested making a copy of `v`, since the input data is not `const`-quaranteed.

**Comment by ben-e-whitney** [comment] 2019-10-28 17:05
I can reproduce this on `master` (bc82ad49767e13056fe04163975746e55c1ce00b).

(Side issue: `obj/mgard_test.o` shouldn't be included in `libmgard.a`. First, it's not needed, and second, it contains a `main` function, which causes linking errors. I'll push a fix to `ornl` today.)

Weirdly, it seems that these points are almost, but not quite, in a corner of the array. (Possibly I am messing up my indexing.)

**Comment by ben-e-whitney** [comment] 2019-10-28 17:57
Not to muddy the waters, but possibly related: running this on `mgard` (5b14862350655a5365b2f36a566f3f89e9dd0470), I get errors in about 40% of the entries of the 215 × 215 array. (There's also one small error in the 9 × 9 array.) I mention this because `mgard` contains 9c55b4d478eccdfcdf5c3f70f7637e59097a7f49, whose commit message

> Fixed the number of projections for non-2^k+1 case. Setting l_target = nlevel -1

suggests the commit might be relevant here.

`mgard`, containing commits from @tugluk and @NAThompson, was never merged into `master`. An oversight?

**Comment by NAThompson** [comment] 2019-10-28 18:02
@ben-e-whitney : I just did `git checkout 9c55b4d` and ran the code above on it. Instead of getting a few errors, I get totally swamped by them.

**Comment by tugluk** [comment] 2019-10-29 23:48
This is most likely more of a "MGARD incorrect on tight tolerances" thing. There is an obvious but costly fix, I'll look into it.

**Comment by NAThompson** [comment] 2019-10-30 20:13
@tugluk : Strangely, I have determined that the minimal allowed tolerance before the code breaks depends on `s`! So if I increase `s` to (say) 2, then the minimal tolerance is much higher than the minimal tolerance if `s=0`.

It appears that for any `thresh`chosen independently of `s`,  `assert(tol > thresh)` can be broken by an judicious choice of `s`.

**Comment by tugluk** [comment] 2019-10-30 20:58
Not strange at all, quantization depends on s. It is not clear what you mean by 2, but the `assert` is much earlier so cannot be broken.

**Comment by NAThompson** [comment] 2019-10-30 23:07
@tugluk : I have already demonstrated that whatever constant you place into the assert, I can find a value of `s` such that the bug reappears.

**Comment by ben-e-whitney** [comment] 2020-03-10 18:36
There are fewer (but not zero) errors when the dimensions are restricted to the form `2^k + 1`. I suggest starting with that case when this is debugged, since it should involve less code.

**Comment by ben-e-whitney** [comment] 2020-09-22 18:44
This has been fixed in the reimplemented `compress` and `decompress` functions added to the API in 1120e92e4e9bf96cbacb9fd0f796456f9986028c. Unzip [this archive][issue_31.zip] in the root of the repository and run the following.

```console
$ git checkout 1120e92e4e9bf96cbacb9fd0f796456f9986028c
$ make lib/libmgard.a bin/ --jobs 8
$ g++ -g -fno-omit-frame-pointer -O3 -march=native -ffast-math -fno-finite-math-only -std=c++11 -fPIC -Iinclude  -c -o obj/issue_31.o issue_31.cpp
$ g++ -g -fno-omit-frame-pointer -O3 -march=native -ffast-math -fno-finite-math-only    obj/issue_31.o lib/libmgard.a -lz -ldl -o bin/issue_31
$ bin/issue_31 
testing decompose–recompose satisfies tolerance on array of size 20 interpreted as a matrix of 4 rows and 5 columns
testing decompose–recompose satisfies tolerance on array of size 30 interpreted as a matrix of 5 rows and 6 columns
testing decompose–recompose satisfies tolerance on array of size 49 interpreted as a matrix of 7 rows and 7 columns
testing decompose–recompose satisfies tolerance on array of size 81 interpreted as a matrix of 9 rows and 9 columns
testing decompose–recompose satisfies tolerance on array of size 144 interpreted as a matrix of 12 rows and 12 columns
testing decompose–recompose satisfies tolerance on array of size 225 interpreted as a matrix of 15 rows and 15 columns
testing decompose–recompose satisfies tolerance on array of size 361 interpreted as a matrix of 19 rows and 19 columns
testing decompose–recompose satisfies tolerance on array of size 600 interpreted as a matrix of 24 rows and 25 columns
testing decompose–recompose satisfies tolerance on array of size 961 interpreted as a matrix of 31 rows and 31 columns
testing decompose–recompose satisfies tolerance on array of size 1560 interpreted as a matrix of 39 rows and 40 columns
testing decompose–recompose satisfies tolerance on array of size 2550 interpreted as a matrix of 50 rows and 51 columns
testing decompose–recompose satisfies tolerance on array of size 4160 interpreted as a matrix of 64 rows and 65 columns
testing decompose–recompose satisfies tolerance on array of size 6724 interpreted as a matrix of 82 rows and 82 columns
testing decompose–recompose satisfies tolerance on array of size 10920 interpreted as a matrix of 104 rows and 105 columns
testing decompose–recompose satisfies tolerance on array of size 17689 interpreted as a matrix of 133 rows and 133 columns
testing decompose–recompose satisfies tolerance on array of size 28561 interpreted as a matrix of 169 rows and 169 columns
testing decompose–recompose satisfies tolerance on array of size 46225 interpreted as a matrix of 215 rows and 215 columns
testing decompose–recompose satisfies tolerance on array of size 74802 interpreted as a matrix of 273 rows and 274 columns
testing decompose–recompose satisfies tolerance on array of size 121104 interpreted as a matrix of 348 rows and 348 columns
testing decompose–recompose satisfies tolerance on array of size 196249 interpreted as a matrix of 443 rows and 443 columns
testing decompose–recompose satisfies tolerance on array of size 317532 interpreted as a matrix of 563 rows and 564 columns
```

I'll leave this issue open till the changes have been merged.

[issue_31.zip]: https://github.com/CODARcode/MGARD/files/5263394/issue_31.zip

**Closed** 2020-09-28 15:06 UTC
Labels: bug
