### ISSUE TITLE
MGARD binary fails to compile

### ISSUE THREAD

**Issue by tugluk** [CODARcode/MGARD#167] opened 2021-11-05 11:30 UTC
* While trying the new release (1.0.0), I had trouble with TCLAP library. To start with my distro doesn't have a tclap.pc for version 1.4. Creating one led to the following error:

`MGARD-1.0.0/include/cmdline.hpp:58:18: error: ‘XorHandler’ in namespace ‘TCLAP’ does not name a type`
 `virtual TCLAP::XorHandler &getXorHandler() override;`
                  ^~~~~~~~~~
`compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/mgard-executable.dir/build.make:90: CMakeFiles/mgard-executable.dir/src/cmdline.cpp.o] Error 1
`

Fixing this will save users a lot of headache and frustruation. Should be fixable by changing CMake method for finding packages, but I don't know how.

* One other issue is, if the user doesn't have zstd libraries, the following error ensues :

`[ 50%] Building CXX object CMakeFiles/mgard-library.dir/src/compressors.cpp.o`
`MGARD-1.0.0/src/compressors.cpp: In function ‘void mgard::decompress_memory_huffman(unsigned char*, std::size_t, long int*, std::size_t)’:`
`MGARD-1.0.0/src/compressors.cpp:293:59: error: cannot convert ‘unsigned char*’ to ‘int*’`
` decompress_memory_z(buf, data_len - 3 * sizeof(size_t), huffman_encoding_p,`
 `                                                          ^~~~~~~~~~~~~~~~~~`
`compilation terminated due to -Wfatal-errors.`

I think this is due to a mismatch between  signatures of  `decompress_memory_z` and `decompress_memory_zstd`, and should be an easy enough fix; by shifting some declerations into the corresponding conditional compilation block. But as-is, MGARD binary fails to compile with zlib.

**Comment by ben-e-whitney** [comment] 2021-11-05 16:46
The first issue seems to have been caused by my not appreciating the implications of the changes made in #141.

1. It appears that TCLAP doesn't generally come with either a PkgConfig `.pc` file or a CMake configuration file. My distribution's TCLAP package happens to contain a PkgConfig `.pc` file:

```console
$ lsb_release --description
Description:	Ubuntu 18.04.6 LTS
$ dpkg-query --status libtclap-dev | grep '^Status: '
Status: install ok installed
$ dpkg --listfiles libtclap-dev | grep '\.pc$'
/usr/lib/x86_64-linux-gnu/pkgconfig/tclap.pc
```
When you install from [source][TCLAP 1.4.0], though, you get neither a PkgConfig `.pc` file nor a CMake configuration file.

[TCLAP 1.4.0]: https://sourceforge.net/projects/tclap/files/

2. The compilation error you're getting is caused by API changes between TCLAP 1.2 (the version `include/cmdline.hpp` uses) and TCLAP 1.4 (the version required in #141).

I'm working on both issues on the `find-tclap` branch. I'll link this issue in the pull request I make.

The second issue might be fixed by #159. Can you checkout 9e057f6c8d2263171ef90294d4548969ac3c350b and see whether you still get the error?

**Closed** 2022-01-11 23:05 UTC
Labels: bug
